#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "holos"
name = "Holos"
description.en = "Identity relay server for mobile Fediverse instances"
description.fr = "Serveur relais d'identité pour instances mobiles Fediverse"

version = "1.0~ynh1"

maintainers = [ ]

[upstream]
license = "AGPL-3.0-only"
website = "https://holos.social/"
admindoc = "https://holos.social/how-it-works"
code = "https://codeberg.org/tom79/Holos-Relay-Server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/tom79/Holos-Relay-Server/archive/1be98526132cea04487a9157dba46e04d5701248.tar.gz"
    sha256 = "adb9e981e518914a26c56adf5d6e51bf2d94d35d29c0d32c1cf761872967b7c2"

    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    server.default = 4000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
