#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "holos"
name = "Holos"
description.en = "Identity relay server for mobile Fediverse instances"
description.fr = "Serveur relais d'identité pour instances mobiles Fediverse"

version = "1.0~ynh1"

maintainers = [ ]

[upstream]
license = "free" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://holos.social/"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://codeberg.org/tom79/Holos-Relay-Server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/foo/bar/archive/refs/tags/v1.2.3.tar.gz"
    sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"