# Proxy settings
location __PATH__/ {
  proxy_pass       http://127.0.0.1:__PORT__/;
  
  include proxy_params_no_auth;
}

# WebSocket support
location __PATH__/socket.io/ {
  proxy_pass       http://127.0.0.1:__PORT__/;
  include proxy_params_no_auth;
}

# Metrics endpoint (requires METRICS_TOKEN)
location __PATH__/metrics {
  proxy_pass       http://127.0.0.1:__PORT__/;
  include proxy_params_no_auth;
}