#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

jwt_secret=$(ynh_string_random --length=64)
ynh_app_setting_set --key=jwt_secret --value=$jwt_secret

token=$(ynh_string_random --length=32)
ynh_app_setting_set --key=token --value=$token

api_key=$(ynh_string_random --length=48)
ynh_app_setting_set --key=api_key --value=$api_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=password --value=$password

password_hash=$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'$password', bcrypt.gensalt(rounds=10)).decode('utf-8'))")

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"
#ynh_write_var_in_file --file="$install_dir/.env" --key="ADMIN_PASSWORD" --value="$password"
#sed -i "s|ADMIN_PASSWORD=.*|ADMIN_PASSWORD=$password|" "$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
ynh_config_add_systemd --service="$app-tunnel" --template="systemd-tunnel.service"

yunohost service add "$app" --description="Identity relay server"

#=================================================
# INSTALL HOLOS
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
#set -a
#source $install_dir/.env

	ynh_hide_warnings ynh_exec_as_app npm install

	# following command is disabled because it will hang on super_admin creation so we create it ourself
	#ynh_hide_warnings ynh_exec_as_app npx tsx scripts/init-db.ts
	##ynh_psql_db_shell <<< "GRANT ALL ON SCHEMA public TO $db_user;"
	##ynh_psql_db_shell <<< "GRANT ALL ON SCHEMA public TO public;"
	##ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON DATABASE $db_name TO $db_user;"
	
	##(echo "SET ROLE $db_user;"; cat src/database/schema.sql) | ynh_psql_db_shell
	##ynh_hide_warnings ynh_exec_as_app npx tsx src/database/run-all-migrations.ts
	##ynh_psql_db_shell <<< "INSERT INTO users (email, password_hash, role, email_verified, created_at, updated_at) VALUES ('$admin_mail', '$password_hash', 'SUPER_ADMIN', true, NOW(), NOW()) ON CONFLICT (email) DO NOTHING;"
	ynh_hide_warnings ynh_exec_as_app ADMIN_EMAIL="$admin_mail" \
		ADMIN_PASSWORD="$password" \
		DB_HOST="localhost" \
		DB_USER="$db_user" \
		DB_PASSWORD="$db_pwd" \
		DB_NAME="$db_name" \
		npx tsx scripts/init-db.ts

	ynh_hide_warnings ynh_exec_as_app npm run build

set +a
   
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="\\[SERVER\\] Running on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
