#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

jwt_secret=$(ynh_string_random --length=64)
token=$(ynh_string_random --length=32)
api_key=$(ynh_string_random --length=48)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Identity relay server" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL HOLOS
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
 	ynh_hide_warnings ynh_exec_as_app npm install
    # following command is disabled because it will hang on super_admin creation so we create it ourself
	#ynh_hide_warnings ynh_exec_as_app npx tsx scripts/init-db.ts
 	ynh_psql_db_shell <<< "INSERT INTO users (email, password_hash, role, email_verified, created_at, updated_at) VALUES ('$admin_mail', '\$2b\$10\$jIC3k/w.m8XRL8YLX5jgz.hCvthxRDzRDchrMgVCCrEkYf2pp/bme', 'SUPER_ADMIN', true, NOW(), NOW()) ON CONFLICT (email) DO NOTHING;"
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
